INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Avenida Lacerda, 590, Liberdade, Salvador - BA', 'Avenida China, 102, Cabralzinho, Macapá - AP', 1, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Nullam nulla mauris, finibus eu accumsan nec', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 2, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Donec sed nibh vitae massa rhoncus iaculis sit amet ac turpis.', 'Cras at egestas enim. Curabitur vehicula ligula id nibh viverra sagittis', 2, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Nunc malesuada nibh pellentesque diam interdum, id rhoncus dui euismod', 'Morbi ut condimentum mauris, eget sagittis nulla. Sed risus turpis', 3, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Vestibulum at justo sodales nisi ultrices facilisis', 'Donec maximus libero eget diam interdum, eget semper nibh viverra. Nulla facilisi. Aenean sagittis blandit elit eu volutpat', 4, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Nulla facilisi. In tempus, arcu eu porta varius', 'Praesent at odio eu mi ultricies facilisis. In eget urna accumsan', 5, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Suspendisse nec tellus sit amet arcu sodales iaculis vitae id orci', 'Etiam auctor, nisi sit amet tristique congue, dui elit mollis ligula', 6, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Cras blandit eu purus non fringilla', 'Aliquam ut ligula condimentum, varius dui eget', 7, NOW());
INSERT INTO entrega(data_para_busca, endereco_destino, endereco_origem, pedido_id, previsao_para_entrega)VALUES(NOW(), 'Phasellus eu eros nibh. Donec volutpat nibh neque, sit amet volutpat turpis pretium et', 'Phasellus et hendrerit massa, at ultricies tellus', 8, NOW());
