INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Travessa Coronel João Teixeira, 718, Conselheiro Paulino, Nova Friburgo', 'RJ', 'Renato e Sophia Publicidade e Propaganda ME');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Praça Samuel Mac Dowell, 403, Taquara, Rio de Janeiro', 'RJ', 'Nathan e Emilly Alimentos ME');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Francisco Dantas, 671, Freguesia (Jacarepaguá)', 'RJ', 'Marcos Vinicius e Kevin Gráfica Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Venceslau Brás, 538, Parque Regina', 'RJ', 'Bernardo e Enrico Marketing Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Getúlio das Neves, 269, Jardim Botânico', 'RJ', 'Giovanni e Pedro Henrique Marketing Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua João Bernardino de Souza, 143, Parque da Cidadania, São José do Rio Preto', 'SP', 'Martin e Renato Ferragens ME');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Jayme Fingerman, 847, Parque Santo Antônio', 'SP', 'Jennifer e Iago Pizzaria Delivery Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua B-14, 983, Jardim Progresso, Ribeirão Preto', 'SP', 'Bárbara e Renan Telecom ME');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua do Bosque, 224, Caputera, Arujá', 'SP', 'Diogo e Hadassa Casa Noturna Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Violeta, 724, São João, João Monlevade', 'MG', 'Sueli e Lucas Marcenaria ME');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua Bela Vista, 744, Vila Paiva, Varginha', 'MG', 'Emily e Marina Telas Ltda');
INSERT INTO fornecedor.fornecedor (endereco, estado, nome) VALUES('Rua José Maria de Magalhães, 231, Centro, Coronel Fabriciano', 'MG', 'Vinicius e Mariane Lavanderia Ltda');
