spring:
  profiles:
    active: dev
  application:
    name: fornecedor
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: NON_NULL
    locale: pt-BR
    time-zone: America/Sao_Paulo
  datasource:
    initialization-mode: always
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fornecedor-dev
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    open-in-view: true
    show_sql: false
    hibernate:
      ddl-auto: none
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: false
trace: false
server:
  compression:
    enabled: true
    min-response-size: 1
  port: 8081
  undertow:
    accesslog:
      dir: logs
      enabled: false
      pattern: '%t %a "%r" %s (%D ms)'
logging:
  level:
    org:
      springframework: warn
      hibernate: warn
      xnio: warn
      jboss: warn
    io:
      undertow: warn
    com:
      zaxxer:
        hikari:
          HikariDataSource: warn
# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: Fornecedor
    description: Micro serviço de fornecedor
    version: 1.2.0
    encoding: UTF-8
    java:
      version: 11
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8001/user
hystrix:
  shareSecurityContext: true