spring:
  profiles:
    active: prod
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fornecedor
    username: root
    password: root
debug: false
trace: false
