spring:
  profiles:
    active: test
  datasource:
    initialization-mode: always
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fornecedor-test
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    open-in-view: true
    show_sql: fasle
    hibernate:
      ddl-auto: none
debug: false
trace: false
