spring:
  profiles:
    active: test
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fornecedor-test
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    open-in-view: true
    show_sql: fasle
    hibernate:
      ddl-auto: none
  sql.init.mode: always
  sql.init.platform: mariadb
debug: false
trace: false
