spring:
  profiles:
    active: prod
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fornecedor
    username: root
    password: root
  sql.init.platform: mariadb
debug: false
trace: false
